### ISSUE TITLE
你好像沒有了解 async 。

### ISSUE THREAD

**Issue by hgalytoby** [AloneAlongLife/MyselfAnimeDownloader_WebUI#1]
我稍微看了一下你程式碼，我發現你應該不了解在 async 底下使用會卡 io 的同步方法會發生什麼事情。

例如 subprocess

https://github.com/AloneAlongLife/MyselfAnimeDownloader_WebUI/blob/master/anime_module/m3u8.py#L128

你應該使用要 async subprocess 

https://docs.python.org/3/library/asyncio-subprocess.html

你如果要用一般寫入檔案的方法你應該要用 async 的套件。

例如你這邊 https://github.com/AloneAlongLife/MyselfAnimeDownloader_WebUI/blob/master/anime_module/m3u8.py#L98

你應該要使用這類的套件

https://github.com/Tinche/aiofiles 或者 https://github.com/alexdelorenzo/aiopath

我稍微看你的程式碼，建議你了解一下 async 不然就用一般 def + thread，當然你覺得程式能跑就好，那就沒問題了。

**Comment by zhihao1021** [comment]
因為這個是把之前的舊代碼直接移植過來，測試的時候都先只有單個影片在下載所以沒有發現，前幾天做多個影片下載的時候看到會噸一下才發現那邊沒有改好😅，現在是先把他用`run_in_executor`包起來，第一次聽說async subprocess，感謝分享。

至於你點出寫入檔案那裏，因為只有單純寫入文件而已，大概上百行左右，我想說應該不會占用多久就忽略過去了。

然後現在修改中的的檔案會放在[development](https://github.com/AloneAlongLife/MyselfAnimeDownloader_WebUI/tree/development)分支(~~因為我前幾個禮拜才開始會用Branch~~)。

這個是我第一次把Async實作到專案裡，感謝指教。

**Comment by zhihao1021** [comment]
如果有其他問題再開個Issue跟我說，用Discord (`YEE#6952`)也可以，回覆會比較快。
